# Generated by Django 2.1.4 on 2020-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_resume_history'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Resume'),
        ),
    ]
