# Generated by Django 2.1.4 on 2020-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_resume_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='current_company',
            field=models.TextField(default='AITS', max_length=100),
        ),
    ]
