# Generated by Django 2.1.4 on 2020-04-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_resume_current_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='current_company',
        ),
    ]
