# Generated by Django 2.1.4 on 2020-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_resume_current_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='facebook',
            field=models.URLField(default='------'),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(default='------'),
        ),
        migrations.AddField(
            model_name='resume',
            name='hobies',
            field=models.TextField(default='cricket'),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(default='------'),
        ),
        migrations.AddField(
            model_name='resume',
            name='mail',
            field=models.EmailField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='resume',
            name='mobile',
            field=models.IntegerField(default='91'),
        ),
        migrations.AddField(
            model_name='resume',
            name='present_company',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='present_role',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(default=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
