# Generated by Django 2.1.4 on 2020-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200417_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=True, max_length=280),
        ),
    ]
