# Generated by Django 2.1.4 on 2020-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200417_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='previous_company',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='previous_role',
            field=models.CharField(choices=[('FR', 'Developer'), ('SO', 'Android_Developer'), ('JR', ' IOS_Developer'), ('SR', 'Frontend_Developer'), ('GR', 'Data_Scientist'), ('SW', 'Software_Developer')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='resume',
            name='your_intro',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='present_role',
            field=models.CharField(choices=[('FR', 'Developer'), ('SO', 'Android_Developer'), ('JR', ' IOS_Developer'), ('SR', 'Frontend_Developer'), ('GR', 'Data_Scientist'), ('SW', 'Software_Developer')], default='FR', max_length=2),
        ),
    ]
