# Generated by Django 2.1.4 on 2020-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200417_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='present_work',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='previous_work',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='previous_role',
            field=models.CharField(choices=[('FR', 'Developer'), ('SO', 'Android_Developer'), ('JR', ' IOS_Developer'), ('SR', 'Frontend_Developer'), ('GR', 'Data_Scientist'), ('SW', 'Software_Developer')], default='GR', max_length=2),
        ),
    ]
