# Generated by Django 2.1.4 on 2020-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20200417_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='present_role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Android Developer', 'Android_Developer'), ('IOS Developer', ' IOS_Developer'), ('Frontend Developer', 'Frontend_Developer'), ('Data Scientist', 'Data_Scientist'), ('Software Developer', 'Software_Developer')], default='Developer', max_length=2),
        ),
        migrations.AlterField(
            model_name='resume',
            name='previous_role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Android Developer', 'Android_Developer'), ('IOS Developer', ' IOS_Developer'), ('Frontend Developer', 'Frontend_Developer'), ('Data Scientist', 'Data_Scientist'), ('Software Developer', 'Software_Developer')], default='Data Scientist', max_length=2),
        ),
    ]
