# Generated by Django 2.1.4 on 2020-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_auto_20200417_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='permanent_address',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
