# Generated by Django 2.1.4 on 2020-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_auto_20200417_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='your_image',
            field=models.FileField(null=True, upload_to='cv/images/'),
        ),
    ]
